# Generated by Django 3.2.8 on 2021-11-13 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('type', models.PositiveIntegerField(choices=[(1, 'hướng'), (2, 'nhóm mục tiêu'), (3, 'địa bàn')])),
            ],
        ),
        migrations.CreateModel(
            name='XFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_submitted', models.DateTimeField(null=True)),
                ('date_approved', models.DateTimeField(null=True)),
                ('status', django_fsm.FSMIntegerField(choices=[(0, 'khởi tạo'), (1, 'đang sửa đổi'), (2, 'đang phê duyệt'), (3, 'đã hoàn thiện')], default=0, protected=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xfiles_approved', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xfiles_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xfiles', to='users.department')),
                ('editors', models.ManyToManyField(null=True, related_name='xfiles_can_edit', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xfiles_submitted', to=settings.AUTH_USER_MODEL)),
                ('targets', models.ManyToManyField(related_name='xfiles', to='xfiles.Target')),
            ],
        ),
        migrations.CreateModel(
            name='XFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='XFileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.IntegerField(default=1, verbose_name=[(0, 'tạo mới'), (1, 'sửa đổi'), (2, 'gửi phê duyệt'), (3, 'phê duyệt'), (4, 'yêu cầu sửa lại'), (5, 'hủy bỏ trạng thái hoàn thiện để tiếp tục sửa đổi')])),
                ('contents', models.TextField(blank=True, null=True)),
                ('attack_logs', models.TextField(blank=True, null=True)),
                ('performer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xfile_logs', to=settings.AUTH_USER_MODEL)),
                ('xfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xfile_logs', to='xfiles.xfile')),
            ],
        ),
        migrations.AddField(
            model_name='xfile',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='xfiles', to='xfiles.xfiletype'),
        ),
        migrations.CreateModel(
            name='ExContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('xfile_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex_contents', to='xfiles.xfiletype')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='xfiles.content')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='xfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='xfiles.xfile'),
        ),
        migrations.CreateModel(
            name='AttackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('process', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('attacker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('xfile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attack_logs', to='xfiles.xfile')),
            ],
        ),
    ]
