# Generated by Django 3.2.8 on 2021-11-14 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xfile',
            name='editors',
            field=models.ManyToManyField(related_name='xfiles_can_edit', to=settings.AUTH_USER_MODEL),
        ),
    ]
