# Generated by Django 3.2.8 on 2021-10-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to='xfiles.content'),
        ),
    ]
