# Generated by Django 3.2.8 on 2021-10-31 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('xfiles', '0002_alter_detail_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='xfile',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xfiles_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xfile',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='xfiles_edited', to=settings.AUTH_USER_MODEL),
        ),
    ]
